apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      name: python
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: marusz/python
        env:
          - name: LOG_LEVEL
            value: "DEBUG"
          - name: REDIS_HOST
            value: "redis-service"